### ISSUE TITLE
How to insert line break between prompt and generated output?

### ISSUE THREAD

**Issue by GenTxt** [robgon-art/DeepHaiku#1]
Have training and generation notebooks working. Just wondering how to print the prompt "My pet pug is" and sample_output on separate lines instead of continuing on same line?

Required output:

My pet pug is
the greatest dog that ever lived. He likes to run around the etc.

After converting notebooks to python scripts have tried adding \n to print statement in various positions but all cause errors.

Would appreciate suggestions.

Deep_Haiku_Train.ipynb

```
with torch.no_grad():
  prompt_tokens2 = tokenizer("My pet pug is", return_tensors="pt").input_ids.cuda()
  sample_outputs = gpt.generate(prompt_tokens2, max_length=40, do_sample=True, temperature=0.9)
  for i, sample_output in enumerate(sample_outputs):
    print("{}: {}".format(i, tokenizer.decode(sample_output, skip_special_tokens=True)))
```

**Comment by robgon-art** [comment]
Hi GenTxt,

Yes, you can do it like this.

```
with torch.no_grad():
  prompt = "My pet pug is"
  prompt_tokens2 = tokenizer(prompt, return_tensors="pt").input_ids.cuda()
  sample_outputs = gpt.generate(prompt_tokens2, max_length=40, do_sample=True, temperature=0.7)
  output = tokenizer.decode(sample_output, skip_special_tokens=True)
  clipped_output = output[len(prompt):].strip()
  print(prompt + "\n" + clipped_output)
```
The output is:

```
My pet pug is
a very loving, caring, and well mannered dog. She is very loyal and never cries. She is very affectionate and treats everyone with love. She is very smart
````

The code simply removes the head of the output based on the length of the prompt.

**Comment by GenTxt** [comment]
Thanks for working code lines.  Added as per below and working 100%

with torch.no_grad():
   prompt_tokens = tokenizer(prompt, return_tensors="pt").input_ids.cuda()
   sample_outputs = gpt.generate(prompt_tokens, min_length=40,
max_length=50, do_sample=True, num_return_sequences=1, top_p=0.9,
repetition_penalty = 1.1, temperature=1.0)
   for i, sample_output in enumerate(sample_outputs):
     output = tokenizer.decode(sample_output, skip_special_tokens=True)
     clipped_output = output[len(prompt):].strip()
     print(prompt + "\n" + clipped_output)
#   print( "\n" + clipped_output) # no prompt
