### ISSUE TITLE
I tried running this code in Google Colab but I just get ValueError: [E966]  every time I try, is there a fix for this?

### ISSUE THREAD

**Issue by machinelearnman** [robgon-art/DeepHaiku#2]
ValueError: [E966] `nlp.add_pipe` now takes the string name of the registered component factory, not a callable component. Expected string, but got <wmd.WMD.SpacySimilarityHook object at 0x7f740c1cf1d0> (name: 'None').

- If you created your component with `nlp.create_pipe('name')`: remove nlp.create_pipe and call `nlp.add_pipe('name')` instead.

- If you passed in a component like `TextCategorizer()`: call `nlp.add_pipe` with the string name instead, e.g. `nlp.add_pipe('textcat')`.

- If you're using a custom component: Add the decorator `@Language.component` (for function components) or `@Language.factory` (for class components / factories) to your custom component and assign it a name, e.g. `@Language.component('your_name')`. You can then run `nlp.add_pipe('your_name')` to add it to the pipeline.

**Comment by robgon-art** [comment]
Hello, thanks for the report. I will check it out...

**Comment by robgon-art** [comment]
OK, the issue is with the GRUEN quality metric. I disabled it for now, so the Colab runs.

**Comment by machinelearnman** [comment]
Thanks for such a quick reply.
